package com.projectMatrix.model;

// Generated Aug 22, 2017 2:42:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClientVertical generated by hbm2java
 */
@Entity
@Table(name = "client_vertical", catalog = "project_matrix")
public class ClientVertical implements java.io.Serializable {

	private Integer verticalId;
	private String verticalName;
	private Set<Client> clients = new HashSet<Client>(0);

	public ClientVertical() {
	}

	public ClientVertical(String verticalName, Set<Client> clients) {
		this.verticalName = verticalName;
		this.clients = clients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vertical_id", unique = true, nullable = false)
	public Integer getVerticalId() {
		return this.verticalId;
	}

	public void setVerticalId(Integer verticalId) {
		this.verticalId = verticalId;
	}

	@Column(name = "vertical_name", length = 250)
	public String getVerticalName() {
		return this.verticalName;
	}

	public void setVerticalName(String verticalName) {
		this.verticalName = verticalName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientVertical")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
