package com.projectMatrix.model;

// Generated Aug 22, 2017 2:42:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JobStage generated by hbm2java
 */
@Entity
@Table(name = "job_stage", catalog = "project_matrix")
public class JobStage implements java.io.Serializable {

	private Long jobStageId;
	private Job job;
	private String jobStatus;
	private String jobStage;
	private Double hoursEstimated;
	private Double hoursSpent;
	private Set<UomStored> uomStoreds = new HashSet<UomStored>(0);

	public JobStage() {
	}

	public JobStage(Job job, String jobStatus, String jobStage,
			Double hoursEstimated, Double hoursSpent, Set<UomStored> uomStoreds) {
		this.job = job;
		this.jobStatus = jobStatus;
		this.jobStage = jobStage;
		this.hoursEstimated = hoursEstimated;
		this.hoursSpent = hoursSpent;
		this.uomStoreds = uomStoreds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "job_stage_id", unique = true, nullable = false)
	public Long getJobStageId() {
		return this.jobStageId;
	}

	public void setJobStageId(Long jobStageId) {
		this.jobStageId = jobStageId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_id")
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Column(name = "job_status", length = 100)
	public String getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	@Column(name = "job_stage", length = 100)
	public String getJobStage() {
		return this.jobStage;
	}

	public void setJobStage(String jobStage) {
		this.jobStage = jobStage;
	}

	@Column(name = "hours_estimated", precision = 22, scale = 0)
	public Double getHoursEstimated() {
		return this.hoursEstimated;
	}

	public void setHoursEstimated(Double hoursEstimated) {
		this.hoursEstimated = hoursEstimated;
	}

	@Column(name = "hours_spent", precision = 22, scale = 0)
	public Double getHoursSpent() {
		return this.hoursSpent;
	}

	public void setHoursSpent(Double hoursSpent) {
		this.hoursSpent = hoursSpent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobStage")
	public Set<UomStored> getUomStoreds() {
		return this.uomStoreds;
	}

	public void setUomStoreds(Set<UomStored> uomStoreds) {
		this.uomStoreds = uomStoreds;
	}

}
