package com.projectMatrix.model;

// Generated Aug 22, 2017 2:42:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProjectUom generated by hbm2java
 */
@Entity
@Table(name = "project_uom", catalog = "project_matrix")
public class ProjectUom implements java.io.Serializable {

	private Long projectUomId;
	private Uom uom;
	private Project project;
	private Set<JobUom> jobUoms = new HashSet<JobUom>(0);

	public ProjectUom() {
	}

	public ProjectUom(Uom uom, Project project, Set<JobUom> jobUoms) {
		this.uom = uom;
		this.project = project;
		this.jobUoms = jobUoms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_uom_id", unique = true, nullable = false)
	public Long getProjectUomId() {
		return this.projectUomId;
	}

	public void setProjectUomId(Long projectUomId) {
		this.projectUomId = projectUomId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "uom_id")
	public Uom getUom() {
		return this.uom;
	}

	public void setUom(Uom uom) {
		this.uom = uom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectUom")
	public Set<JobUom> getJobUoms() {
		return this.jobUoms;
	}

	public void setJobUoms(Set<JobUom> jobUoms) {
		this.jobUoms = jobUoms;
	}

}
