package com.projectMatrix.model;

// Generated Nov 16, 2017 1:21:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActionPointTracker generated by hbm2java
 */
@Entity
@Table(name = "action_point_tracker", catalog = "project_matrix")
public class ActionPointTracker implements java.io.Serializable {

	private Long aptId;
	private Resource resourceByAssignedFrom;
	private Resource resourceByAssignedTo;
	private Date createdDate;
	private Date startDate;
	private Date endDate;
	private String subject;
	private String description;
	private String priority;
	private String status;
	private String stackHolders;
	private Set<AptRemarks> aptRemarkses = new HashSet<AptRemarks>(0);

	public ActionPointTracker() {
	}

	public ActionPointTracker(Resource resourceByAssignedFrom,
			Resource resourceByAssignedTo, Date createdDate, Date startDate,
			Date endDate, String subject, String description, String priority,
			String status, String stackHolders, Set<AptRemarks> aptRemarkses) {
		this.resourceByAssignedFrom = resourceByAssignedFrom;
		this.resourceByAssignedTo = resourceByAssignedTo;
		this.createdDate = createdDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.subject = subject;
		this.description = description;
		this.priority = priority;
		this.status = status;
		this.stackHolders = stackHolders;
		this.aptRemarkses = aptRemarkses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "apt_id", unique = true, nullable = false)
	public Long getAptId() {
		return this.aptId;
	}

	public void setAptId(Long aptId) {
		this.aptId = aptId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assigned_from")
	public Resource getResourceByAssignedFrom() {
		return this.resourceByAssignedFrom;
	}

	public void setResourceByAssignedFrom(Resource resourceByAssignedFrom) {
		this.resourceByAssignedFrom = resourceByAssignedFrom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assigned_to")
	public Resource getResourceByAssignedTo() {
		return this.resourceByAssignedTo;
	}

	public void setResourceByAssignedTo(Resource resourceByAssignedTo) {
		this.resourceByAssignedTo = resourceByAssignedTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "subject", length = 1000)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "description", length = 20000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "priority", length = 45)
	public String getPriority() {
		return this.priority;
	}

	public void setPriority(String priority) {
		this.priority = priority;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "stack_holders", length = 500)
	public String getStackHolders() {
		return this.stackHolders;
	}

	public void setStackHolders(String stackHolders) {
		this.stackHolders = stackHolders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actionPointTracker")
	public Set<AptRemarks> getAptRemarkses() {
		return this.aptRemarkses;
	}

	public void setAptRemarkses(Set<AptRemarks> aptRemarkses) {
		this.aptRemarkses = aptRemarkses;
	}

}
