package com.projectMatrix.model;

// Generated Nov 16, 2017 1:21:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AptRemarks generated by hbm2java
 */
@Entity
@Table(name = "apt_remarks", catalog = "project_matrix")
public class AptRemarks implements java.io.Serializable {

	private Long aptRemarksId;
	private Resource resource;
	private ActionPointTracker actionPointTracker;
	private String remarks;
	private Date createdDate;

	public AptRemarks() {
	}

	public AptRemarks(Resource resource, ActionPointTracker actionPointTracker,
			String remarks, Date createdDate) {
		this.resource = resource;
		this.actionPointTracker = actionPointTracker;
		this.remarks = remarks;
		this.createdDate = createdDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "apt_remarks_id", unique = true, nullable = false)
	public Long getAptRemarksId() {
		return this.aptRemarksId;
	}

	public void setAptRemarksId(Long aptRemarksId) {
		this.aptRemarksId = aptRemarksId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_id_fk")
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "apt_id_fk")
	public ActionPointTracker getActionPointTracker() {
		return this.actionPointTracker;
	}

	public void setActionPointTracker(ActionPointTracker actionPointTracker) {
		this.actionPointTracker = actionPointTracker;
	}

	@Column(name = "remarks", length = 20000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

}
