package com.projectMatrix.model;

// Generated Nov 16, 2017 1:21:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", catalog = "project_matrix")
public class Invoice implements java.io.Serializable {

	private Long invoiceId;
	private Project project;
	private JobCompleted jobCompleted;
	private Integer clientId;
	private String invoiceNo;
	private Date invoiceDate;
	private Date approvalJobDate;
	private Double invoiceAmount;
	private Date receivedDate;
	private Double receivedAmount;
	private Double balanceAmount;
	private String remarks;

	public Invoice() {
	}

	public Invoice(Project project, JobCompleted jobCompleted,
			Integer clientId, String invoiceNo, Date invoiceDate,
			Date approvalJobDate, Double invoiceAmount, Date receivedDate,
			Double receivedAmount, Double balanceAmount, String remarks) {
		this.project = project;
		this.jobCompleted = jobCompleted;
		this.clientId = clientId;
		this.invoiceNo = invoiceNo;
		this.invoiceDate = invoiceDate;
		this.approvalJobDate = approvalJobDate;
		this.invoiceAmount = invoiceAmount;
		this.receivedDate = receivedDate;
		this.receivedAmount = receivedAmount;
		this.balanceAmount = balanceAmount;
		this.remarks = remarks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "invoice_id", unique = true, nullable = false)
	public Long getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Long invoiceId) {
		this.invoiceId = invoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_id")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jobs_completed")
	public JobCompleted getJobCompleted() {
		return this.jobCompleted;
	}

	public void setJobCompleted(JobCompleted jobCompleted) {
		this.jobCompleted = jobCompleted;
	}

	@Column(name = "client_id")
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@Column(name = "invoice_no", length = 100)
	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "invoice_date", length = 10)
	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "approval_job_date", length = 10)
	public Date getApprovalJobDate() {
		return this.approvalJobDate;
	}

	public void setApprovalJobDate(Date approvalJobDate) {
		this.approvalJobDate = approvalJobDate;
	}

	@Column(name = "invoice_amount", precision = 22, scale = 0)
	public Double getInvoiceAmount() {
		return this.invoiceAmount;
	}

	public void setInvoiceAmount(Double invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "received_date", length = 10)
	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	@Column(name = "received_amount", precision = 22, scale = 0)
	public Double getReceivedAmount() {
		return this.receivedAmount;
	}

	public void setReceivedAmount(Double receivedAmount) {
		this.receivedAmount = receivedAmount;
	}

	@Column(name = "balance_amount", precision = 22, scale = 0)
	public Double getBalanceAmount() {
		return this.balanceAmount;
	}

	public void setBalanceAmount(Double balanceAmount) {
		this.balanceAmount = balanceAmount;
	}

	@Column(name = "remarks", length = 1000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
