package com.projectMatrix.model;

// Generated Nov 16, 2017 1:21:18 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JobUom generated by hbm2java
 */
@Entity
@Table(name = "job_uom", catalog = "project_matrix")
public class JobUom implements java.io.Serializable {

	private Long jobUomId;
	private ProjectUom projectUom;
	private Job job;
	private Integer value;

	public JobUom() {
	}

	public JobUom(ProjectUom projectUom, Job job, Integer value) {
		this.projectUom = projectUom;
		this.job = job;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "job_uom_id", unique = true, nullable = false)
	public Long getJobUomId() {
		return this.jobUomId;
	}

	public void setJobUomId(Long jobUomId) {
		this.jobUomId = jobUomId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_uom_id")
	public ProjectUom getProjectUom() {
		return this.projectUom;
	}

	public void setProjectUom(ProjectUom projectUom) {
		this.projectUom = projectUom;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "job_id")
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	@Column(name = "value")
	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

}
