package com.projectMatrix.model;

// Generated Nov 16, 2017 1:21:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "project_matrix", uniqueConstraints = @UniqueConstraint(columnNames = "cent_project_code"))
public class Project implements java.io.Serializable {

	private Long projectId;
	private Resource resource;
	private Client client;
	private String endCustomer;
	private String operationRegion;
	private String workRegion;
	private String clientPm;
	private String projectCode;
	private String centProjectCode;
	private String projectName;
	private String projectScope;
	private String costCenter;
	private String offshorePm;
	private Date startDate;
	private Date endDate;
	private Integer inputValidationPercentage;
	private Integer productionPercentage;
	private Integer qcPercentage;
	private Integer qaPercentage;
	private Integer deliveryPercentage;
	private Integer feedbackPercentage;
	private Integer redeliveryPercentage;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);
	private Set<Job> jobs = new HashSet<Job>(0);
	private Set<ProjectUom> projectUoms = new HashSet<ProjectUom>(0);
	private Set<TeamMembers> teamMemberses = new HashSet<TeamMembers>(0);
	private Set<UomStored> uomStoreds = new HashSet<UomStored>(0);

	public Project() {
	}

	public Project(Resource resource, Client client, String endCustomer,
			String operationRegion, String workRegion, String clientPm,
			String projectCode, String centProjectCode, String projectName,
			String projectScope, String costCenter, String offshorePm,
			Date startDate, Date endDate, Integer inputValidationPercentage,
			Integer productionPercentage, Integer qcPercentage,
			Integer qaPercentage, Integer deliveryPercentage,
			Integer feedbackPercentage, Integer redeliveryPercentage,
			Set<Invoice> invoices, Set<Job> jobs, Set<ProjectUom> projectUoms,
			Set<TeamMembers> teamMemberses, Set<UomStored> uomStoreds) {
		this.resource = resource;
		this.client = client;
		this.endCustomer = endCustomer;
		this.operationRegion = operationRegion;
		this.workRegion = workRegion;
		this.clientPm = clientPm;
		this.projectCode = projectCode;
		this.centProjectCode = centProjectCode;
		this.projectName = projectName;
		this.projectScope = projectScope;
		this.costCenter = costCenter;
		this.offshorePm = offshorePm;
		this.startDate = startDate;
		this.endDate = endDate;
		this.inputValidationPercentage = inputValidationPercentage;
		this.productionPercentage = productionPercentage;
		this.qcPercentage = qcPercentage;
		this.qaPercentage = qaPercentage;
		this.deliveryPercentage = deliveryPercentage;
		this.feedbackPercentage = feedbackPercentage;
		this.redeliveryPercentage = redeliveryPercentage;
		this.invoices = invoices;
		this.jobs = jobs;
		this.projectUoms = projectUoms;
		this.teamMemberses = teamMemberses;
		this.uomStoreds = uomStoreds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_id", unique = true, nullable = false)
	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "team_lead")
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_id")
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Column(name = "end_customer", length = 100)
	public String getEndCustomer() {
		return this.endCustomer;
	}

	public void setEndCustomer(String endCustomer) {
		this.endCustomer = endCustomer;
	}

	@Column(name = "operation_region", length = 100)
	public String getOperationRegion() {
		return this.operationRegion;
	}

	public void setOperationRegion(String operationRegion) {
		this.operationRegion = operationRegion;
	}

	@Column(name = "work_region", length = 100)
	public String getWorkRegion() {
		return this.workRegion;
	}

	public void setWorkRegion(String workRegion) {
		this.workRegion = workRegion;
	}

	@Column(name = "client_pm", length = 100)
	public String getClientPm() {
		return this.clientPm;
	}

	public void setClientPm(String clientPm) {
		this.clientPm = clientPm;
	}

	@Column(name = "project_code", length = 250)
	public String getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	@Column(name = "cent_project_code", unique = true, length = 100)
	public String getCentProjectCode() {
		return this.centProjectCode;
	}

	public void setCentProjectCode(String centProjectCode) {
		this.centProjectCode = centProjectCode;
	}

	@Column(name = "project_name", length = 250)
	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	@Column(name = "project_scope", length = 100)
	public String getProjectScope() {
		return this.projectScope;
	}

	public void setProjectScope(String projectScope) {
		this.projectScope = projectScope;
	}

	@Column(name = "cost_center", length = 100)
	public String getCostCenter() {
		return this.costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	@Column(name = "offshore_pm", length = 100)
	public String getOffshorePm() {
		return this.offshorePm;
	}

	public void setOffshorePm(String offshorePm) {
		this.offshorePm = offshorePm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "input_validation_percentage")
	public Integer getInputValidationPercentage() {
		return this.inputValidationPercentage;
	}

	public void setInputValidationPercentage(Integer inputValidationPercentage) {
		this.inputValidationPercentage = inputValidationPercentage;
	}

	@Column(name = "production_percentage")
	public Integer getProductionPercentage() {
		return this.productionPercentage;
	}

	public void setProductionPercentage(Integer productionPercentage) {
		this.productionPercentage = productionPercentage;
	}

	@Column(name = "qc_percentage")
	public Integer getQcPercentage() {
		return this.qcPercentage;
	}

	public void setQcPercentage(Integer qcPercentage) {
		this.qcPercentage = qcPercentage;
	}

	@Column(name = "qa_percentage")
	public Integer getQaPercentage() {
		return this.qaPercentage;
	}

	public void setQaPercentage(Integer qaPercentage) {
		this.qaPercentage = qaPercentage;
	}

	@Column(name = "delivery_percentage")
	public Integer getDeliveryPercentage() {
		return this.deliveryPercentage;
	}

	public void setDeliveryPercentage(Integer deliveryPercentage) {
		this.deliveryPercentage = deliveryPercentage;
	}

	@Column(name = "feedback_percentage")
	public Integer getFeedbackPercentage() {
		return this.feedbackPercentage;
	}

	public void setFeedbackPercentage(Integer feedbackPercentage) {
		this.feedbackPercentage = feedbackPercentage;
	}

	@Column(name = "redelivery_percentage")
	public Integer getRedeliveryPercentage() {
		return this.redeliveryPercentage;
	}

	public void setRedeliveryPercentage(Integer redeliveryPercentage) {
		this.redeliveryPercentage = redeliveryPercentage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<Job> getJobs() {
		return this.jobs;
	}

	public void setJobs(Set<Job> jobs) {
		this.jobs = jobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<ProjectUom> getProjectUoms() {
		return this.projectUoms;
	}

	public void setProjectUoms(Set<ProjectUom> projectUoms) {
		this.projectUoms = projectUoms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<TeamMembers> getTeamMemberses() {
		return this.teamMemberses;
	}

	public void setTeamMemberses(Set<TeamMembers> teamMemberses) {
		this.teamMemberses = teamMemberses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "project")
	public Set<UomStored> getUomStoreds() {
		return this.uomStoreds;
	}

	public void setUomStoreds(Set<UomStored> uomStoreds) {
		this.uomStoreds = uomStoreds;
	}

}
