package com.projectMatrix.model;

// Generated Nov 16, 2017 1:21:18 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResourceAllocation generated by hbm2java
 */
@Entity
@Table(name = "resource_allocation", catalog = "project_matrix")
public class ResourceAllocation implements java.io.Serializable {

	private Long resourceAllocatedId;
	private Resource resourceByQaAllocatedId;
	private Resource resourceByFeedbackAllocatedId;
	private Resource resourceByProductionAllocatedId;
	private Resource resourceByQcAllocatedId;
	private Job job;

	public ResourceAllocation() {
	}

	public ResourceAllocation(Resource resourceByQaAllocatedId,
			Resource resourceByFeedbackAllocatedId,
			Resource resourceByProductionAllocatedId,
			Resource resourceByQcAllocatedId, Job job) {
		this.resourceByQaAllocatedId = resourceByQaAllocatedId;
		this.resourceByFeedbackAllocatedId = resourceByFeedbackAllocatedId;
		this.resourceByProductionAllocatedId = resourceByProductionAllocatedId;
		this.resourceByQcAllocatedId = resourceByQcAllocatedId;
		this.job = job;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "resource_allocated_id", unique = true, nullable = false)
	public Long getResourceAllocatedId() {
		return this.resourceAllocatedId;
	}

	public void setResourceAllocatedId(Long resourceAllocatedId) {
		this.resourceAllocatedId = resourceAllocatedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qa_allocated_id")
	public Resource getResourceByQaAllocatedId() {
		return this.resourceByQaAllocatedId;
	}

	public void setResourceByQaAllocatedId(Resource resourceByQaAllocatedId) {
		this.resourceByQaAllocatedId = resourceByQaAllocatedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "feedback_allocated_id")
	public Resource getResourceByFeedbackAllocatedId() {
		return this.resourceByFeedbackAllocatedId;
	}

	public void setResourceByFeedbackAllocatedId(
			Resource resourceByFeedbackAllocatedId) {
		this.resourceByFeedbackAllocatedId = resourceByFeedbackAllocatedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "production_allocated_id")
	public Resource getResourceByProductionAllocatedId() {
		return this.resourceByProductionAllocatedId;
	}

	public void setResourceByProductionAllocatedId(
			Resource resourceByProductionAllocatedId) {
		this.resourceByProductionAllocatedId = resourceByProductionAllocatedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "qc_allocated_id")
	public Resource getResourceByQcAllocatedId() {
		return this.resourceByQcAllocatedId;
	}

	public void setResourceByQcAllocatedId(Resource resourceByQcAllocatedId) {
		this.resourceByQcAllocatedId = resourceByQcAllocatedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_allocated_job_id")
	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

}
