package com.projectMatrix.model;

// Generated Nov 16, 2017 1:21:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "project_matrix", uniqueConstraints = @UniqueConstraint(columnNames = "emp_id"))
public class Resource implements java.io.Serializable {

	private Long resourceId;
	private Dept dept;
	private SubDept subDept;
	private String empId;
	private String firstName;
	private String middleName;
	private String lastName;
	private Long mobileNo;
	private Long altMobileNo;
	private String officialEmail;
	private String personalEmail;
	private Long emgContactNo;
	private Date dob;
	private Date doj;
	private String curntAdress;
	private String prmtAddress;
	private Integer totYrsExp;
	private String role;
	private String designation;
	private String projectsWorkedOn;
	private String projectScope;
	private String visas;
	private String skills;
	private String performanceLevel;
	private Set<ResourceAllocation> resourceAllocationsForFeedbackAllocatedId = new HashSet<ResourceAllocation>(
			0);
	private Set<ActionPointTracker> actionPointTrackersForAssignedFrom = new HashSet<ActionPointTracker>(
			0);
	private Set<Job> jobs = new HashSet<Job>(0);
	private Set<ResourceAllocation> resourceAllocationsForQcAllocatedId = new HashSet<ResourceAllocation>(
			0);
	private Set<WorkBench> workBenches = new HashSet<WorkBench>(0);
	private Set<ActionPointTracker> actionPointTrackersForAssignedTo = new HashSet<ActionPointTracker>(
			0);
	private Set<ResourceAllocation> resourceAllocationsForQaAllocatedId = new HashSet<ResourceAllocation>(
			0);
	private Set<AptRemarks> aptRemarkses = new HashSet<AptRemarks>(0);
	private Set<ResourceAllocation> resourceAllocationsForProductionAllocatedId = new HashSet<ResourceAllocation>(
			0);
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<UserInfo> userInfos = new HashSet<UserInfo>(0);
	private Set<TeamMembers> teamMemberses = new HashSet<TeamMembers>(0);

	public Resource() {
	}

	public Resource(
			Dept dept,
			SubDept subDept,
			String empId,
			String firstName,
			String middleName,
			String lastName,
			Long mobileNo,
			Long altMobileNo,
			String officialEmail,
			String personalEmail,
			Long emgContactNo,
			Date dob,
			Date doj,
			String curntAdress,
			String prmtAddress,
			Integer totYrsExp,
			String role,
			String designation,
			String projectsWorkedOn,
			String projectScope,
			String visas,
			String skills,
			String performanceLevel,
			Set<ResourceAllocation> resourceAllocationsForFeedbackAllocatedId,
			Set<ActionPointTracker> actionPointTrackersForAssignedFrom,
			Set<Job> jobs,
			Set<ResourceAllocation> resourceAllocationsForQcAllocatedId,
			Set<WorkBench> workBenches,
			Set<ActionPointTracker> actionPointTrackersForAssignedTo,
			Set<ResourceAllocation> resourceAllocationsForQaAllocatedId,
			Set<AptRemarks> aptRemarkses,
			Set<ResourceAllocation> resourceAllocationsForProductionAllocatedId,
			Set<Project> projects, Set<UserInfo> userInfos,
			Set<TeamMembers> teamMemberses) {
		this.dept = dept;
		this.subDept = subDept;
		this.empId = empId;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.mobileNo = mobileNo;
		this.altMobileNo = altMobileNo;
		this.officialEmail = officialEmail;
		this.personalEmail = personalEmail;
		this.emgContactNo = emgContactNo;
		this.dob = dob;
		this.doj = doj;
		this.curntAdress = curntAdress;
		this.prmtAddress = prmtAddress;
		this.totYrsExp = totYrsExp;
		this.role = role;
		this.designation = designation;
		this.projectsWorkedOn = projectsWorkedOn;
		this.projectScope = projectScope;
		this.visas = visas;
		this.skills = skills;
		this.performanceLevel = performanceLevel;
		this.resourceAllocationsForFeedbackAllocatedId = resourceAllocationsForFeedbackAllocatedId;
		this.actionPointTrackersForAssignedFrom = actionPointTrackersForAssignedFrom;
		this.jobs = jobs;
		this.resourceAllocationsForQcAllocatedId = resourceAllocationsForQcAllocatedId;
		this.workBenches = workBenches;
		this.actionPointTrackersForAssignedTo = actionPointTrackersForAssignedTo;
		this.resourceAllocationsForQaAllocatedId = resourceAllocationsForQaAllocatedId;
		this.aptRemarkses = aptRemarkses;
		this.resourceAllocationsForProductionAllocatedId = resourceAllocationsForProductionAllocatedId;
		this.projects = projects;
		this.userInfos = userInfos;
		this.teamMemberses = teamMemberses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "resource_id", unique = true, nullable = false)
	public Long getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Long resourceId) {
		this.resourceId = resourceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dept")
	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sub_dept")
	public SubDept getSubDept() {
		return this.subDept;
	}

	public void setSubDept(SubDept subDept) {
		this.subDept = subDept;
	}

	@Column(name = "emp_id", unique = true, length = 100)
	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	@Column(name = "first_name", length = 100)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name", length = 100)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", length = 100)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "mobile_no")
	public Long getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(Long mobileNo) {
		this.mobileNo = mobileNo;
	}

	@Column(name = "alt_mobile_no")
	public Long getAltMobileNo() {
		return this.altMobileNo;
	}

	public void setAltMobileNo(Long altMobileNo) {
		this.altMobileNo = altMobileNo;
	}

	@Column(name = "official_email", length = 100)
	public String getOfficialEmail() {
		return this.officialEmail;
	}

	public void setOfficialEmail(String officialEmail) {
		this.officialEmail = officialEmail;
	}

	@Column(name = "personal_email", length = 100)
	public String getPersonalEmail() {
		return this.personalEmail;
	}

	public void setPersonalEmail(String personalEmail) {
		this.personalEmail = personalEmail;
	}

	@Column(name = "emg_contact_no")
	public Long getEmgContactNo() {
		return this.emgContactNo;
	}

	public void setEmgContactNo(Long emgContactNo) {
		this.emgContactNo = emgContactNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "doj", length = 10)
	public Date getDoj() {
		return this.doj;
	}

	public void setDoj(Date doj) {
		this.doj = doj;
	}

	@Column(name = "curnt_adress", length = 500)
	public String getCurntAdress() {
		return this.curntAdress;
	}

	public void setCurntAdress(String curntAdress) {
		this.curntAdress = curntAdress;
	}

	@Column(name = "prmt_address", length = 500)
	public String getPrmtAddress() {
		return this.prmtAddress;
	}

	public void setPrmtAddress(String prmtAddress) {
		this.prmtAddress = prmtAddress;
	}

	@Column(name = "tot_yrs_exp")
	public Integer getTotYrsExp() {
		return this.totYrsExp;
	}

	public void setTotYrsExp(Integer totYrsExp) {
		this.totYrsExp = totYrsExp;
	}

	@Column(name = "role", length = 100)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "designation", length = 100)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@Column(name = "projects_worked_on", length = 1000)
	public String getProjectsWorkedOn() {
		return this.projectsWorkedOn;
	}

	public void setProjectsWorkedOn(String projectsWorkedOn) {
		this.projectsWorkedOn = projectsWorkedOn;
	}

	@Column(name = "project_scope", length = 500)
	public String getProjectScope() {
		return this.projectScope;
	}

	public void setProjectScope(String projectScope) {
		this.projectScope = projectScope;
	}

	@Column(name = "visas", length = 100)
	public String getVisas() {
		return this.visas;
	}

	public void setVisas(String visas) {
		this.visas = visas;
	}

	@Column(name = "skills", length = 1000)
	public String getSkills() {
		return this.skills;
	}

	public void setSkills(String skills) {
		this.skills = skills;
	}

	@Column(name = "performance_level", length = 1000)
	public String getPerformanceLevel() {
		return this.performanceLevel;
	}

	public void setPerformanceLevel(String performanceLevel) {
		this.performanceLevel = performanceLevel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceByFeedbackAllocatedId")
	public Set<ResourceAllocation> getResourceAllocationsForFeedbackAllocatedId() {
		return this.resourceAllocationsForFeedbackAllocatedId;
	}

	public void setResourceAllocationsForFeedbackAllocatedId(
			Set<ResourceAllocation> resourceAllocationsForFeedbackAllocatedId) {
		this.resourceAllocationsForFeedbackAllocatedId = resourceAllocationsForFeedbackAllocatedId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceByAssignedFrom")
	public Set<ActionPointTracker> getActionPointTrackersForAssignedFrom() {
		return this.actionPointTrackersForAssignedFrom;
	}

	public void setActionPointTrackersForAssignedFrom(
			Set<ActionPointTracker> actionPointTrackersForAssignedFrom) {
		this.actionPointTrackersForAssignedFrom = actionPointTrackersForAssignedFrom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<Job> getJobs() {
		return this.jobs;
	}

	public void setJobs(Set<Job> jobs) {
		this.jobs = jobs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceByQcAllocatedId")
	public Set<ResourceAllocation> getResourceAllocationsForQcAllocatedId() {
		return this.resourceAllocationsForQcAllocatedId;
	}

	public void setResourceAllocationsForQcAllocatedId(
			Set<ResourceAllocation> resourceAllocationsForQcAllocatedId) {
		this.resourceAllocationsForQcAllocatedId = resourceAllocationsForQcAllocatedId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<WorkBench> getWorkBenches() {
		return this.workBenches;
	}

	public void setWorkBenches(Set<WorkBench> workBenches) {
		this.workBenches = workBenches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceByAssignedTo")
	public Set<ActionPointTracker> getActionPointTrackersForAssignedTo() {
		return this.actionPointTrackersForAssignedTo;
	}

	public void setActionPointTrackersForAssignedTo(
			Set<ActionPointTracker> actionPointTrackersForAssignedTo) {
		this.actionPointTrackersForAssignedTo = actionPointTrackersForAssignedTo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceByQaAllocatedId")
	public Set<ResourceAllocation> getResourceAllocationsForQaAllocatedId() {
		return this.resourceAllocationsForQaAllocatedId;
	}

	public void setResourceAllocationsForQaAllocatedId(
			Set<ResourceAllocation> resourceAllocationsForQaAllocatedId) {
		this.resourceAllocationsForQaAllocatedId = resourceAllocationsForQaAllocatedId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<AptRemarks> getAptRemarkses() {
		return this.aptRemarkses;
	}

	public void setAptRemarkses(Set<AptRemarks> aptRemarkses) {
		this.aptRemarkses = aptRemarkses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resourceByProductionAllocatedId")
	public Set<ResourceAllocation> getResourceAllocationsForProductionAllocatedId() {
		return this.resourceAllocationsForProductionAllocatedId;
	}

	public void setResourceAllocationsForProductionAllocatedId(
			Set<ResourceAllocation> resourceAllocationsForProductionAllocatedId) {
		this.resourceAllocationsForProductionAllocatedId = resourceAllocationsForProductionAllocatedId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<UserInfo> getUserInfos() {
		return this.userInfos;
	}

	public void setUserInfos(Set<UserInfo> userInfos) {
		this.userInfos = userInfos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<TeamMembers> getTeamMemberses() {
		return this.teamMemberses;
	}

	public void setTeamMemberses(Set<TeamMembers> teamMemberses) {
		this.teamMemberses = teamMemberses;
	}

}
