package com.projectMatrix.model;

// Generated Nov 16, 2017 1:21:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name = "user_info", catalog = "project_matrix")
public class UserInfo implements java.io.Serializable {

	private Long userInfoId;
	private Resource resource;
	private String password;
	private String securiyQuestion;
	private String answer;
	private Date doc;

	public UserInfo() {
	}

	public UserInfo(Resource resource, String password, String securiyQuestion,
			String answer, Date doc) {
		this.resource = resource;
		this.password = password;
		this.securiyQuestion = securiyQuestion;
		this.answer = answer;
		this.doc = doc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_info_id", unique = true, nullable = false)
	public Long getUserInfoId() {
		return this.userInfoId;
	}

	public void setUserInfoId(Long userInfoId) {
		this.userInfoId = userInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "emp_id_fk")
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@Column(name = "password", length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "securiy_question", length = 200)
	public String getSecuriyQuestion() {
		return this.securiyQuestion;
	}

	public void setSecuriyQuestion(String securiyQuestion) {
		this.securiyQuestion = securiyQuestion;
	}

	@Column(name = "answer", length = 200)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "doc", length = 10)
	public Date getDoc() {
		return this.doc;
	}

	public void setDoc(Date doc) {
		this.doc = doc;
	}

}
