package com.projectMatrix.model;

// Generated Nov 16, 2017 1:21:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkBench generated by hbm2java
 */
@Entity
@Table(name = "work_bench", catalog = "project_matrix")
public class WorkBench implements java.io.Serializable {

	private Long workBenchId;
	private Resource resource;
	private Date doc;
	private String workedOn;
	private String remarks;
	private Double estimatedTime;
	private Double spentTime;
	private Double onBench;
	private Double inTraining;
	private Double PM;
	private Double others;
	private Double jobStageSpentTime;
	private Set<WorkbenchJob> workbenchJobs = new HashSet<WorkbenchJob>(0);

	public WorkBench() {
	}

	public WorkBench(Resource resource, Date doc, String workedOn,
			String remarks, Double estimatedTime, Double spentTime,
			Double onBench, Double inTraining, Double PM, Double others,
			Double jobStageSpentTime, Set<WorkbenchJob> workbenchJobs) {
		this.resource = resource;
		this.doc = doc;
		this.workedOn = workedOn;
		this.remarks = remarks;
		this.estimatedTime = estimatedTime;
		this.spentTime = spentTime;
		this.onBench = onBench;
		this.inTraining = inTraining;
		this.PM = PM;
		this.others = others;
		this.jobStageSpentTime = jobStageSpentTime;
		this.workbenchJobs = workbenchJobs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "work_bench_id", unique = true, nullable = false)
	public Long getWorkBenchId() {
		return this.workBenchId;
	}

	public void setWorkBenchId(Long workBenchId) {
		this.workBenchId = workBenchId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resource_fk")
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "doc", length = 10)
	public Date getDoc() {
		return this.doc;
	}

	public void setDoc(Date doc) {
		this.doc = doc;
	}

	@Column(name = "worked_on", length = 45)
	public String getWorkedOn() {
		return this.workedOn;
	}

	public void setWorkedOn(String workedOn) {
		this.workedOn = workedOn;
	}

	@Column(name = "remarks", length = 1000)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "estimated_time", precision = 22, scale = 0)
	public Double getEstimatedTime() {
		return this.estimatedTime;
	}

	public void setEstimatedTime(Double estimatedTime) {
		this.estimatedTime = estimatedTime;
	}

	@Column(name = "spent_time", precision = 22, scale = 0)
	public Double getSpentTime() {
		return this.spentTime;
	}

	public void setSpentTime(Double spentTime) {
		this.spentTime = spentTime;
	}

	@Column(name = "on_bench", precision = 22, scale = 0)
	public Double getOnBench() {
		return this.onBench;
	}

	public void setOnBench(Double onBench) {
		this.onBench = onBench;
	}

	@Column(name = "in_training", precision = 22, scale = 0)
	public Double getInTraining() {
		return this.inTraining;
	}

	public void setInTraining(Double inTraining) {
		this.inTraining = inTraining;
	}

	@Column(name = "p_m", precision = 22, scale = 0)
	public Double getPM() {
		return this.PM;
	}

	public void setPM(Double PM) {
		this.PM = PM;
	}

	@Column(name = "others", precision = 22, scale = 0)
	public Double getOthers() {
		return this.others;
	}

	public void setOthers(Double others) {
		this.others = others;
	}

	@Column(name = "job_stage_spentTime", precision = 22, scale = 0)
	public Double getJobStageSpentTime() {
		return this.jobStageSpentTime;
	}

	public void setJobStageSpentTime(Double jobStageSpentTime) {
		this.jobStageSpentTime = jobStageSpentTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workBench")
	public Set<WorkbenchJob> getWorkbenchJobs() {
		return this.workbenchJobs;
	}

	public void setWorkbenchJobs(Set<WorkbenchJob> workbenchJobs) {
		this.workbenchJobs = workbenchJobs;
	}

}
