package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client implements java.io.Serializable {

	private Integer clientId;
	private ClientVertical clientVertical;
	private String clientName;
	private Set projects = new HashSet(0);

	public Client() {
	}

	public Client(ClientVertical clientVertical, String clientName, Set projects) {
		this.clientVertical = clientVertical;
		this.clientName = clientName;
		this.projects = projects;
	}

	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	public ClientVertical getClientVertical() {
		return this.clientVertical;
	}

	public void setClientVertical(ClientVertical clientVertical) {
		this.clientVertical = clientVertical;
	}

	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public Set getProjects() {
		return this.projects;
	}

	public void setProjects(Set projects) {
		this.projects = projects;
	}

}
