package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * ClientVertical generated by hbm2java
 */
public class ClientVertical implements java.io.Serializable {

	private Integer verticalId;
	private String verticalName;
	private Set clients = new HashSet(0);

	public ClientVertical() {
	}

	public ClientVertical(String verticalName, Set clients) {
		this.verticalName = verticalName;
		this.clients = clients;
	}

	public Integer getVerticalId() {
		return this.verticalId;
	}

	public void setVerticalId(Integer verticalId) {
		this.verticalId = verticalId;
	}

	public String getVerticalName() {
		return this.verticalName;
	}

	public void setVerticalName(String verticalName) {
		this.verticalName = verticalName;
	}

	public Set getClients() {
		return this.clients;
	}

	public void setClients(Set clients) {
		this.clients = clients;
	}

}
