package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice implements java.io.Serializable {

	private Long invoiceId;
	private Project project;
	private JobCompleted jobCompleted;
	private Integer clientId;
	private String invoiceNo;
	private Date invoiceDate;
	private Date approvalJobDate;
	private Double invoiceAmount;
	private Date receivedDate;
	private Double receivedAmount;
	private Double balanceAmount;
	private String remarks;

	public Invoice() {
	}

	public Invoice(Project project, JobCompleted jobCompleted,
			Integer clientId, String invoiceNo, Date invoiceDate,
			Date approvalJobDate, Double invoiceAmount, Date receivedDate,
			Double receivedAmount, Double balanceAmount, String remarks) {
		this.project = project;
		this.jobCompleted = jobCompleted;
		this.clientId = clientId;
		this.invoiceNo = invoiceNo;
		this.invoiceDate = invoiceDate;
		this.approvalJobDate = approvalJobDate;
		this.invoiceAmount = invoiceAmount;
		this.receivedDate = receivedDate;
		this.receivedAmount = receivedAmount;
		this.balanceAmount = balanceAmount;
		this.remarks = remarks;
	}

	public Long getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(Long invoiceId) {
		this.invoiceId = invoiceId;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public JobCompleted getJobCompleted() {
		return this.jobCompleted;
	}

	public void setJobCompleted(JobCompleted jobCompleted) {
		this.jobCompleted = jobCompleted;
	}

	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	public Date getInvoiceDate() {
		return this.invoiceDate;
	}

	public void setInvoiceDate(Date invoiceDate) {
		this.invoiceDate = invoiceDate;
	}

	public Date getApprovalJobDate() {
		return this.approvalJobDate;
	}

	public void setApprovalJobDate(Date approvalJobDate) {
		this.approvalJobDate = approvalJobDate;
	}

	public Double getInvoiceAmount() {
		return this.invoiceAmount;
	}

	public void setInvoiceAmount(Double invoiceAmount) {
		this.invoiceAmount = invoiceAmount;
	}

	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	public Double getReceivedAmount() {
		return this.receivedAmount;
	}

	public void setReceivedAmount(Double receivedAmount) {
		this.receivedAmount = receivedAmount;
	}

	public Double getBalanceAmount() {
		return this.balanceAmount;
	}

	public void setBalanceAmount(Double balanceAmount) {
		this.balanceAmount = balanceAmount;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
