package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job implements java.io.Serializable {

	private long jobId;
	private Project project;
	private String jobNo;
	private String jobName;
	private String jobStage;
	private String jobStatus;
	private Date receivedDate;
	private Date assignedDate;
	private Date expectedDelivery;
	private Date deliveredOn;
	private Integer hoursSpent;
	private Date lastModified;
	private String remarks;
	private String jobCriticality;
	private Set jobStages = new HashSet(0);
	private Set resourceAllocations = new HashSet(0);
	private Set jobCompleteds = new HashSet(0);

	public Job() {
	}

	public Job(long jobId) {
		this.jobId = jobId;
	}

	public Job(long jobId, Project project, String jobNo, String jobName,
			String jobStage, String jobStatus, Date receivedDate,
			Date assignedDate, Date expectedDelivery, Date deliveredOn,
			Integer hoursSpent, Date lastModified, String remarks,
			String jobCriticality, Set jobStages, Set resourceAllocations,
			Set jobCompleteds) {
		this.jobId = jobId;
		this.project = project;
		this.jobNo = jobNo;
		this.jobName = jobName;
		this.jobStage = jobStage;
		this.jobStatus = jobStatus;
		this.receivedDate = receivedDate;
		this.assignedDate = assignedDate;
		this.expectedDelivery = expectedDelivery;
		this.deliveredOn = deliveredOn;
		this.hoursSpent = hoursSpent;
		this.lastModified = lastModified;
		this.remarks = remarks;
		this.jobCriticality = jobCriticality;
		this.jobStages = jobStages;
		this.resourceAllocations = resourceAllocations;
		this.jobCompleteds = jobCompleteds;
	}

	public long getJobId() {
		return this.jobId;
	}

	public void setJobId(long jobId) {
		this.jobId = jobId;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public String getJobNo() {
		return this.jobNo;
	}

	public void setJobNo(String jobNo) {
		this.jobNo = jobNo;
	}

	public String getJobName() {
		return this.jobName;
	}

	public void setJobName(String jobName) {
		this.jobName = jobName;
	}

	public String getJobStage() {
		return this.jobStage;
	}

	public void setJobStage(String jobStage) {
		this.jobStage = jobStage;
	}

	public String getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	public Date getReceivedDate() {
		return this.receivedDate;
	}

	public void setReceivedDate(Date receivedDate) {
		this.receivedDate = receivedDate;
	}

	public Date getAssignedDate() {
		return this.assignedDate;
	}

	public void setAssignedDate(Date assignedDate) {
		this.assignedDate = assignedDate;
	}

	public Date getExpectedDelivery() {
		return this.expectedDelivery;
	}

	public void setExpectedDelivery(Date expectedDelivery) {
		this.expectedDelivery = expectedDelivery;
	}

	public Date getDeliveredOn() {
		return this.deliveredOn;
	}

	public void setDeliveredOn(Date deliveredOn) {
		this.deliveredOn = deliveredOn;
	}

	public Integer getHoursSpent() {
		return this.hoursSpent;
	}

	public void setHoursSpent(Integer hoursSpent) {
		this.hoursSpent = hoursSpent;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getJobCriticality() {
		return this.jobCriticality;
	}

	public void setJobCriticality(String jobCriticality) {
		this.jobCriticality = jobCriticality;
	}

	public Set getJobStages() {
		return this.jobStages;
	}

	public void setJobStages(Set jobStages) {
		this.jobStages = jobStages;
	}

	public Set getResourceAllocations() {
		return this.resourceAllocations;
	}

	public void setResourceAllocations(Set resourceAllocations) {
		this.resourceAllocations = resourceAllocations;
	}

	public Set getJobCompleteds() {
		return this.jobCompleteds;
	}

	public void setJobCompleteds(Set jobCompleteds) {
		this.jobCompleteds = jobCompleteds;
	}

}
