package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * JobStage generated by hbm2java
 */
public class JobStage implements java.io.Serializable {

	private Long jobStageId;
	private Job job;
	private Integer hoursSpent;
	private String jobStatus;
	private Set uomStoreds = new HashSet(0);

	public JobStage() {
	}

	public JobStage(Job job, Integer hoursSpent, String jobStatus,
			Set uomStoreds) {
		this.job = job;
		this.hoursSpent = hoursSpent;
		this.jobStatus = jobStatus;
		this.uomStoreds = uomStoreds;
	}

	public Long getJobStageId() {
		return this.jobStageId;
	}

	public void setJobStageId(Long jobStageId) {
		this.jobStageId = jobStageId;
	}

	public Job getJob() {
		return this.job;
	}

	public void setJob(Job job) {
		this.job = job;
	}

	public Integer getHoursSpent() {
		return this.hoursSpent;
	}

	public void setHoursSpent(Integer hoursSpent) {
		this.hoursSpent = hoursSpent;
	}

	public String getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(String jobStatus) {
		this.jobStatus = jobStatus;
	}

	public Set getUomStoreds() {
		return this.uomStoreds;
	}

	public void setUomStoreds(Set uomStoreds) {
		this.uomStoreds = uomStoreds;
	}

}
