package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Performance generated by hbm2java
 */
public class Performance implements java.io.Serializable {

	private Integer performanceId;
	private String performanceLevelName;
	private Integer performanceScale;
	private Set resources = new HashSet(0);

	public Performance() {
	}

	public Performance(String performanceLevelName, Integer performanceScale,
			Set resources) {
		this.performanceLevelName = performanceLevelName;
		this.performanceScale = performanceScale;
		this.resources = resources;
	}

	public Integer getPerformanceId() {
		return this.performanceId;
	}

	public void setPerformanceId(Integer performanceId) {
		this.performanceId = performanceId;
	}

	public String getPerformanceLevelName() {
		return this.performanceLevelName;
	}

	public void setPerformanceLevelName(String performanceLevelName) {
		this.performanceLevelName = performanceLevelName;
	}

	public Integer getPerformanceScale() {
		return this.performanceScale;
	}

	public void setPerformanceScale(Integer performanceScale) {
		this.performanceScale = performanceScale;
	}

	public Set getResources() {
		return this.resources;
	}

	public void setResources(Set resources) {
		this.resources = resources;
	}

}
