package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

	private Long projectId;
	private Client client;
	private Resource resource;
	private String endCustomer;
	private String operationRegion;
	private String workRegion;
	private String clientPm;
	private String projectCode;
	private String centProjectCode;
	private String projectName;
	private String projectScope;
	private String costCenter;
	private String offshorePm;
	private Long projectcol;
	private Date startDate;
	private Date endDate;
	private String CFT1;
	private String CFT2;
	private String CFT3;
	private String CFT4;
	private String CFT5;
	private String CFD1;
	private String CFD2;
	private String CFD3;
	private String CFD4;
	private String CFD5;
	private Set uoms = new HashSet(0);
	private Set teamMemberses = new HashSet(0);
	private Set jobs = new HashSet(0);
	private Set invoices = new HashSet(0);

	public Project() {
	}

	public Project(Client client, Resource resource, String endCustomer,
			String operationRegion, String workRegion, String clientPm,
			String projectCode, String centProjectCode, String projectName,
			String projectScope, String costCenter, String offshorePm,
			Long projectcol, Date startDate, Date endDate, String CFT1,
			String CFT2, String CFT3, String CFT4, String CFT5, String CFD1,
			String CFD2, String CFD3, String CFD4, String CFD5, Set uoms,
			Set teamMemberses, Set jobs, Set invoices) {
		this.client = client;
		this.resource = resource;
		this.endCustomer = endCustomer;
		this.operationRegion = operationRegion;
		this.workRegion = workRegion;
		this.clientPm = clientPm;
		this.projectCode = projectCode;
		this.centProjectCode = centProjectCode;
		this.projectName = projectName;
		this.projectScope = projectScope;
		this.costCenter = costCenter;
		this.offshorePm = offshorePm;
		this.projectcol = projectcol;
		this.startDate = startDate;
		this.endDate = endDate;
		this.CFT1 = CFT1;
		this.CFT2 = CFT2;
		this.CFT3 = CFT3;
		this.CFT4 = CFT4;
		this.CFT5 = CFT5;
		this.CFD1 = CFD1;
		this.CFD2 = CFD2;
		this.CFD3 = CFD3;
		this.CFD4 = CFD4;
		this.CFD5 = CFD5;
		this.uoms = uoms;
		this.teamMemberses = teamMemberses;
		this.jobs = jobs;
		this.invoices = invoices;
	}

	public Long getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	public String getEndCustomer() {
		return this.endCustomer;
	}

	public void setEndCustomer(String endCustomer) {
		this.endCustomer = endCustomer;
	}

	public String getOperationRegion() {
		return this.operationRegion;
	}

	public void setOperationRegion(String operationRegion) {
		this.operationRegion = operationRegion;
	}

	public String getWorkRegion() {
		return this.workRegion;
	}

	public void setWorkRegion(String workRegion) {
		this.workRegion = workRegion;
	}

	public String getClientPm() {
		return this.clientPm;
	}

	public void setClientPm(String clientPm) {
		this.clientPm = clientPm;
	}

	public String getProjectCode() {
		return this.projectCode;
	}

	public void setProjectCode(String projectCode) {
		this.projectCode = projectCode;
	}

	public String getCentProjectCode() {
		return this.centProjectCode;
	}

	public void setCentProjectCode(String centProjectCode) {
		this.centProjectCode = centProjectCode;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getProjectScope() {
		return this.projectScope;
	}

	public void setProjectScope(String projectScope) {
		this.projectScope = projectScope;
	}

	public String getCostCenter() {
		return this.costCenter;
	}

	public void setCostCenter(String costCenter) {
		this.costCenter = costCenter;
	}

	public String getOffshorePm() {
		return this.offshorePm;
	}

	public void setOffshorePm(String offshorePm) {
		this.offshorePm = offshorePm;
	}

	public Long getProjectcol() {
		return this.projectcol;
	}

	public void setProjectcol(Long projectcol) {
		this.projectcol = projectcol;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getCFT1() {
		return this.CFT1;
	}

	public void setCFT1(String CFT1) {
		this.CFT1 = CFT1;
	}

	public String getCFT2() {
		return this.CFT2;
	}

	public void setCFT2(String CFT2) {
		this.CFT2 = CFT2;
	}

	public String getCFT3() {
		return this.CFT3;
	}

	public void setCFT3(String CFT3) {
		this.CFT3 = CFT3;
	}

	public String getCFT4() {
		return this.CFT4;
	}

	public void setCFT4(String CFT4) {
		this.CFT4 = CFT4;
	}

	public String getCFT5() {
		return this.CFT5;
	}

	public void setCFT5(String CFT5) {
		this.CFT5 = CFT5;
	}

	public String getCFD1() {
		return this.CFD1;
	}

	public void setCFD1(String CFD1) {
		this.CFD1 = CFD1;
	}

	public String getCFD2() {
		return this.CFD2;
	}

	public void setCFD2(String CFD2) {
		this.CFD2 = CFD2;
	}

	public String getCFD3() {
		return this.CFD3;
	}

	public void setCFD3(String CFD3) {
		this.CFD3 = CFD3;
	}

	public String getCFD4() {
		return this.CFD4;
	}

	public void setCFD4(String CFD4) {
		this.CFD4 = CFD4;
	}

	public String getCFD5() {
		return this.CFD5;
	}

	public void setCFD5(String CFD5) {
		this.CFD5 = CFD5;
	}

	public Set getUoms() {
		return this.uoms;
	}

	public void setUoms(Set uoms) {
		this.uoms = uoms;
	}

	public Set getTeamMemberses() {
		return this.teamMemberses;
	}

	public void setTeamMemberses(Set teamMemberses) {
		this.teamMemberses = teamMemberses;
	}

	public Set getJobs() {
		return this.jobs;
	}

	public void setJobs(Set jobs) {
		this.jobs = jobs;
	}

	public Set getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set invoices) {
		this.invoices = invoices;
	}

}
