package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Resource generated by hbm2java
 */
public class Resource implements java.io.Serializable {

	private Long resourceId;
	private SubDept subDept;
	private Dept dept;
	private Skills skills;
	private Performance performance;
	private String empId;
	private String firstName;
	private String middleName;
	private String lastName;
	private Long mobileNo;
	private Long altMobileNo;
	private String officialEmail;
	private String personalEmail;
	private Long emgContactNo;
	private Date dob;
	private Date doj;
	private String curntAdress;
	private String prmtAddress;
	private Integer totYrsExp;
	private String role;
	private String designation;
	private String projectsWorkedOn;
	private String projectScope;
	private String visas;
	private Set teamMemberses = new HashSet(0);
	private Set projects = new HashSet(0);
	private Set resourceAllocationsForQaAllocatedId = new HashSet(0);
	private Set resourceAllocationsForQcAllocatedId = new HashSet(0);
	private Set resourceAllocationsForProductionAllocatedId = new HashSet(0);
	private Set resourceAllocationsForFeedbackAllocatedId = new HashSet(0);

	public Resource() {
	}

	public Resource(SubDept subDept, Dept dept, Skills skills,
			Performance performance, String empId, String firstName,
			String middleName, String lastName, Long mobileNo,
			Long altMobileNo, String officialEmail, String personalEmail,
			Long emgContactNo, Date dob, Date doj, String curntAdress,
			String prmtAddress, Integer totYrsExp, String role,
			String designation, String projectsWorkedOn, String projectScope,
			String visas, Set teamMemberses, Set projects,
			Set resourceAllocationsForQaAllocatedId,
			Set resourceAllocationsForQcAllocatedId,
			Set resourceAllocationsForProductionAllocatedId,
			Set resourceAllocationsForFeedbackAllocatedId) {
		this.subDept = subDept;
		this.dept = dept;
		this.skills = skills;
		this.performance = performance;
		this.empId = empId;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.mobileNo = mobileNo;
		this.altMobileNo = altMobileNo;
		this.officialEmail = officialEmail;
		this.personalEmail = personalEmail;
		this.emgContactNo = emgContactNo;
		this.dob = dob;
		this.doj = doj;
		this.curntAdress = curntAdress;
		this.prmtAddress = prmtAddress;
		this.totYrsExp = totYrsExp;
		this.role = role;
		this.designation = designation;
		this.projectsWorkedOn = projectsWorkedOn;
		this.projectScope = projectScope;
		this.visas = visas;
		this.teamMemberses = teamMemberses;
		this.projects = projects;
		this.resourceAllocationsForQaAllocatedId = resourceAllocationsForQaAllocatedId;
		this.resourceAllocationsForQcAllocatedId = resourceAllocationsForQcAllocatedId;
		this.resourceAllocationsForProductionAllocatedId = resourceAllocationsForProductionAllocatedId;
		this.resourceAllocationsForFeedbackAllocatedId = resourceAllocationsForFeedbackAllocatedId;
	}

	public Long getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Long resourceId) {
		this.resourceId = resourceId;
	}

	public SubDept getSubDept() {
		return this.subDept;
	}

	public void setSubDept(SubDept subDept) {
		this.subDept = subDept;
	}

	public Dept getDept() {
		return this.dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public Skills getSkills() {
		return this.skills;
	}

	public void setSkills(Skills skills) {
		this.skills = skills;
	}

	public Performance getPerformance() {
		return this.performance;
	}

	public void setPerformance(Performance performance) {
		this.performance = performance;
	}

	public String getEmpId() {
		return this.empId;
	}

	public void setEmpId(String empId) {
		this.empId = empId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Long getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(Long mobileNo) {
		this.mobileNo = mobileNo;
	}

	public Long getAltMobileNo() {
		return this.altMobileNo;
	}

	public void setAltMobileNo(Long altMobileNo) {
		this.altMobileNo = altMobileNo;
	}

	public String getOfficialEmail() {
		return this.officialEmail;
	}

	public void setOfficialEmail(String officialEmail) {
		this.officialEmail = officialEmail;
	}

	public String getPersonalEmail() {
		return this.personalEmail;
	}

	public void setPersonalEmail(String personalEmail) {
		this.personalEmail = personalEmail;
	}

	public Long getEmgContactNo() {
		return this.emgContactNo;
	}

	public void setEmgContactNo(Long emgContactNo) {
		this.emgContactNo = emgContactNo;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	public Date getDoj() {
		return this.doj;
	}

	public void setDoj(Date doj) {
		this.doj = doj;
	}

	public String getCurntAdress() {
		return this.curntAdress;
	}

	public void setCurntAdress(String curntAdress) {
		this.curntAdress = curntAdress;
	}

	public String getPrmtAddress() {
		return this.prmtAddress;
	}

	public void setPrmtAddress(String prmtAddress) {
		this.prmtAddress = prmtAddress;
	}

	public Integer getTotYrsExp() {
		return this.totYrsExp;
	}

	public void setTotYrsExp(Integer totYrsExp) {
		this.totYrsExp = totYrsExp;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getProjectsWorkedOn() {
		return this.projectsWorkedOn;
	}

	public void setProjectsWorkedOn(String projectsWorkedOn) {
		this.projectsWorkedOn = projectsWorkedOn;
	}

	public String getProjectScope() {
		return this.projectScope;
	}

	public void setProjectScope(String projectScope) {
		this.projectScope = projectScope;
	}

	public String getVisas() {
		return this.visas;
	}

	public void setVisas(String visas) {
		this.visas = visas;
	}

	public Set getTeamMemberses() {
		return this.teamMemberses;
	}

	public void setTeamMemberses(Set teamMemberses) {
		this.teamMemberses = teamMemberses;
	}

	public Set getProjects() {
		return this.projects;
	}

	public void setProjects(Set projects) {
		this.projects = projects;
	}

	public Set getResourceAllocationsForQaAllocatedId() {
		return this.resourceAllocationsForQaAllocatedId;
	}

	public void setResourceAllocationsForQaAllocatedId(
			Set resourceAllocationsForQaAllocatedId) {
		this.resourceAllocationsForQaAllocatedId = resourceAllocationsForQaAllocatedId;
	}

	public Set getResourceAllocationsForQcAllocatedId() {
		return this.resourceAllocationsForQcAllocatedId;
	}

	public void setResourceAllocationsForQcAllocatedId(
			Set resourceAllocationsForQcAllocatedId) {
		this.resourceAllocationsForQcAllocatedId = resourceAllocationsForQcAllocatedId;
	}

	public Set getResourceAllocationsForProductionAllocatedId() {
		return this.resourceAllocationsForProductionAllocatedId;
	}

	public void setResourceAllocationsForProductionAllocatedId(
			Set resourceAllocationsForProductionAllocatedId) {
		this.resourceAllocationsForProductionAllocatedId = resourceAllocationsForProductionAllocatedId;
	}

	public Set getResourceAllocationsForFeedbackAllocatedId() {
		return this.resourceAllocationsForFeedbackAllocatedId;
	}

	public void setResourceAllocationsForFeedbackAllocatedId(
			Set resourceAllocationsForFeedbackAllocatedId) {
		this.resourceAllocationsForFeedbackAllocatedId = resourceAllocationsForFeedbackAllocatedId;
	}

}
