package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Skills generated by hbm2java
 */
public class Skills implements java.io.Serializable {

	private Integer skillsId;
	private String skillsName;
	private Integer skillsScale;
	private Set resources = new HashSet(0);

	public Skills() {
	}

	public Skills(String skillsName, Integer skillsScale, Set resources) {
		this.skillsName = skillsName;
		this.skillsScale = skillsScale;
		this.resources = resources;
	}

	public Integer getSkillsId() {
		return this.skillsId;
	}

	public void setSkillsId(Integer skillsId) {
		this.skillsId = skillsId;
	}

	public String getSkillsName() {
		return this.skillsName;
	}

	public void setSkillsName(String skillsName) {
		this.skillsName = skillsName;
	}

	public Integer getSkillsScale() {
		return this.skillsScale;
	}

	public void setSkillsScale(Integer skillsScale) {
		this.skillsScale = skillsScale;
	}

	public Set getResources() {
		return this.resources;
	}

	public void setResources(Set resources) {
		this.resources = resources;
	}

}
