package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * SubDept generated by hbm2java
 */
public class SubDept implements java.io.Serializable {

	private Integer subDeptId;
	private String subDeptName;
	private Set resources = new HashSet(0);

	public SubDept() {
	}

	public SubDept(String subDeptName, Set resources) {
		this.subDeptName = subDeptName;
		this.resources = resources;
	}

	public Integer getSubDeptId() {
		return this.subDeptId;
	}

	public void setSubDeptId(Integer subDeptId) {
		this.subDeptId = subDeptId;
	}

	public String getSubDeptName() {
		return this.subDeptName;
	}

	public void setSubDeptName(String subDeptName) {
		this.subDeptName = subDeptName;
	}

	public Set getResources() {
		return this.resources;
	}

	public void setResources(Set resources) {
		this.resources = resources;
	}

}
