package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

/**
 * TeamMembers generated by hbm2java
 */
public class TeamMembers implements java.io.Serializable {

	private Integer tmId;
	private Resource resource;
	private Project project;
	private String keyResourceIndication;

	public TeamMembers() {
	}

	public TeamMembers(Resource resource, Project project,
			String keyResourceIndication) {
		this.resource = resource;
		this.project = project;
		this.keyResourceIndication = keyResourceIndication;
	}

	public Integer getTmId() {
		return this.tmId;
	}

	public void setTmId(Integer tmId) {
		this.tmId = tmId;
	}

	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public String getKeyResourceIndication() {
		return this.keyResourceIndication;
	}

	public void setKeyResourceIndication(String keyResourceIndication) {
		this.keyResourceIndication = keyResourceIndication;
	}

}
