package com.projectMatrix.model;

// Generated Jul 23, 2017 3:14:16 PM by Hibernate Tools 4.0.0

/**
 * UomStored generated by hbm2java
 */
public class UomStored implements java.io.Serializable {

	private int uomStoredId;
	private Uom uom;
	private JobStage jobStage;
	private Integer value;

	public UomStored() {
	}

	public UomStored(int uomStoredId) {
		this.uomStoredId = uomStoredId;
	}

	public UomStored(int uomStoredId, Uom uom, JobStage jobStage, Integer value) {
		this.uomStoredId = uomStoredId;
		this.uom = uom;
		this.jobStage = jobStage;
		this.value = value;
	}

	public int getUomStoredId() {
		return this.uomStoredId;
	}

	public void setUomStoredId(int uomStoredId) {
		this.uomStoredId = uomStoredId;
	}

	public Uom getUom() {
		return this.uom;
	}

	public void setUom(Uom uom) {
		this.uom = uom;
	}

	public JobStage getJobStage() {
		return this.jobStage;
	}

	public void setJobStage(JobStage jobStage) {
		this.jobStage = jobStage;
	}

	public Integer getValue() {
		return this.value;
	}

	public void setValue(Integer value) {
		this.value = value;
	}

}
